pub mod binary_diff;
pub mod comparison;
pub mod csv_diff;
pub mod excel_diff;
pub mod file_operations;
pub mod hash_cache;
pub mod image_diff;
pub mod json_diff;
pub mod parquet_diff;
pub mod scanner;
pub mod text_diff;
pub mod vfs;

pub use binary_diff::BinaryDiffEngine;
pub use comparison::ComparisonEngine;
pub use csv_diff::{is_csv_file, CsvCompareMode, CsvDiffEngine, CsvDiffResult};
pub use excel_diff::{is_excel_file, ExcelDiffEngine, ExcelDiffResult};
pub use file_operations::FileOperations;
pub use hash_cache::HashCache;
pub use image_diff::{is_image_file, ImageCompareMode, ImageDiffEngine, ImageDiffResult};
pub use json_diff::{is_json_file, is_yaml_file, JsonDiffEngine, JsonDiffResult};
pub use parquet_diff::{is_parquet_file, ParquetDiffEngine, ParquetDiffResult};
pub use scanner::FolderScanner;
pub use text_diff::TextDiffEngine;
pub use vfs::LocalVfs;
